import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const resources = {
  he: {
    translation: {
      home: 'בית',
      products: 'מוצרים',
      profile: 'פרופיל',
      about: 'אודות',
      more: 'עוד',
      barBook: 'ספר בר',
      orders: 'הזמנות',
      itemsManagement: 'ניהול מוצרים',
      navItemsMgmt: 'מלאי',
      cart: 'עגלת קניות',
      recipes: 'מתכונים',
      // Landing page
      landingTagline: 'מערכת ניהול בר חכמה לשמירת סדר, מלאי והזמנות',
      landingLoginTitle: 'כניסה למערכת',
      landingSignupTitle: 'יצירת חשבון חדש',
      landingLoginBtn: 'כניסה',
      landingSignupBtn: 'יצירת חשבון',
      alreadyMember: 'כבר רשום? לחץ להתחברות',
      newUser: 'משתמש חדש? לחץ להירשם',
      fullnamePlaceholder: 'שם מלא',
      usernamePlaceholder: 'שם משתמש',
      passwordPlaceholder: 'סיסמה',
      welcomeMsg: 'ברוך הבא!',
      loginError: 'שם משתמש או סיסמה שגויים',
      featureInventoryTitle: 'ניהול מלאי',
      featureInventoryDesc: 'עקוב אחר מוצרים, מחירים והתראות מלאי נמוך',
      featureOrdersTitle: 'הזמנות לספקים',
      featureOrdersDesc: 'צור ונהל הזמנות ישירות מרשימת המלאי',
      featureBarBookTitle: 'ספר בר',
      featureBarBookDesc: 'צ׳קליסטים, משימות יומיות ומתכונים במקום אחד',
      featureDashboardTitle: 'דשבורד',
      featureDashboardDesc: 'סקירה כללית של הפעילות בזמן אמת',
      // Home page
      dailyTask: 'משימה יומית',
      day_0: 'ראשון',
      day_1: 'שני',
      day_2: 'שלישי',
      day_3: 'רביעי',
      day_4: 'חמישי',
      day_5: 'שישי',
      day_6: 'שבת',
      dayPrefix: 'יום',
      dailyTaskFallback: 'בדוק מלאי ועדכן את ספר הבר',
      supplierOrdersSummaryTitle: 'כמות הזמנות לפי ספק ומוצר',
      supplierOrdersTotalUnits: 'יחידות בסה"כ',
      supplierOrdersProduct: 'מוצר',
      supplierOrdersQty: 'כמות',
      statTotalProducts: 'סה"כ מוצרים',
      statAvailableProducts: 'מוצרים זמינים',
      statLowStock: 'מלאי נמוך',
      statTotalOrders: 'סה"כ הזמנות',
      statPendingOrders: 'הזמנות ממתינות',
      statTodayRevenue: 'הכנסות היום',
      lowStockAlerts: 'התראות מלאי נמוך',
      stockLabel: 'מלאי',
      alertThresholdLabel: 'רף התראה',
      selectItemPrompt: 'בחרי פריט מהרשימה',
      volumeMlLabel: 'מ״ל לבקבוק',
      volumeMlPlaceholder: 'נפח בקבוק במ״ל (לדוגמה 700)',
      stockLevel: 'מפלס מלאי',
      totalVolume: 'סה״כ נפח במלאי',
      ml: 'מ״ל',
      litre: 'ליטר',
      suggestedOrder: 'הזמנה מוצעת',
      quantityToOrder: 'כמות להשלמה',
      updateStock: 'עדכון מלאי',
      decrease: 'הפחתה',
      increase: 'הוספה',
      unitsInStock: 'יחידות במלאי',
      unitsByCategory: 'יחידות לפי קטגוריה',
      unitsOrderedPerDay: 'יחידות שהוזמנו לפי יום',
      unitsOrdered: 'יחידות שהוזמנו',
      lastNDays: '{{n}} ימים אחרונים',
      allStockOk: 'כל המלאי תקין',
      selectOrderPrompt: 'בחרי הזמנה מהרשימה',
      summary: 'סיכום',
      totalUnitsLabel: 'סה״כ יחידות',
      viewAllLowStock: 'צפה בכל המוצרים עם מלאי נמוך',
      recentOrders: 'הזמנות אחרונות',
      viewAll: 'צפה בהכל',
      orderId: 'הזמנה',
      itemsCount: 'פריטים',
      status_pending: 'ממתין',
      status_completed: 'הושלם',
      status_delivered: 'נמסר',
      // Header
      hello: 'שלום',
      logout: 'התנתק',
      switchUser: 'החלף משתמש',
      logoutSuccess: 'להתראות!',
      loginRequired: 'יש להתחבר תחילה',
      toggleLanguage: 'החלף שפה',
      openSidebar: 'פתח תפריט',
      closeSidebar: 'סגור תפריט',
      // Bar Book
      barBookTitle: 'ספר בר',
      tabChecklists: 'צ\'קליסטים',
      tabPages: 'דפי מלאים',
      tabDaily: 'משימות יומיות',
      tabRecipes: 'מתכונים',
      editMode: 'עריכה',
      exitEditMode: 'סיום עריכה',
      loadingBarBook: 'טוען ספר בר...',
      pageErrorTitle: 'העמוד הזה הפסיק לעבוד',
      pageErrorBody: 'שאר האפליקציה עדיין זמינה מהתפריט. אפשר לנסות שוב או לרענן.',
      pageErrorRetry: 'נסי שוב',
      pageErrorReload: 'רענון',
      errorLoadBarBook: 'שגיאה בטעינת ספר הבר',
      barBookConflict: 'משתמש אחר עדכן את ספר הבר. רענני את הדף כדי לראות את הגרסה העדכנית.',
      // Bar Book run mode
      newShift: 'משמרת חדשה',
      confirmNewShift: 'לנקות {{count}} סימונים ולהתחיל משמרת חדשה?',
      editModeOn: 'סיום עריכה',
      doneOfTotal: '{{done}} מתוך {{total}}',
      back: 'חזרה',
      dailyTasksTitle: 'משימות יומיות',
      dailyTasksIntro: 'משימות יומיות מתבצעות בכל משמרת. המשימה מתבצעת לפי יום בשבוע.',
      clickToEdit: 'לחץ לעריכה',
      deleteRow: 'מחק שורה',
      deleteItem: 'מחק משימה',
      deleteDay: 'מחק יום',
      addTask: 'הוסף משימה',
      clearContent: 'נקה תוכן',
      addPage: 'הוסף עמוד',
      pageTitlePlaceholder: 'שם העמוד...',
      confirmDeletePage: 'למחוק את העמוד הזה?',
      typeChecklists: "צ'קליסט",
      typeChecklist: 'רשימה',
      typeTable: 'טבלה',
      columnPresetsLabel: 'עמודות להתחלה (אופציונלי)',
      recipeImportTitle: 'הוסף מתכונים',
      recipeImport_write: 'כתיבה',
      recipeImport_paste: 'הדבקת טקסט',
      recipeImport_excel: 'ייבוא מאקסל',
      recipeImportPasteHint: 'הדבק מתכון אחד או כמה, בכל פורמט. נזהה את המצרכים והכמויות ונציג לאישורך.',
      recipeImportPastePlaceholder: 'נגרוני · 30 מ״ל ג׳ין · 30 מ״ל קמפרי · 30 מ״ל ורמוט מתוק · לערבב עם קרח ולסנן...',
      recipeImportExcelHint: 'קובץ עם עמודות: שם, מצרכים (שורה לכל מצרך), הוראות. ההתאמה נעשית מקומית — בלי עלות.',
      recipeImportRead: 'קרא מתכונים',
      recipeImportReading: 'קורא...',
      recipeImportNoRecipes: 'לא נמצא מתכון משקה בטקסט הזה',
      recipeImportNoRows: 'לא נמצאו שורות מתאימות בקובץ',
      recipeImportNotConfigured: 'ייבוא מתכונים לא מוגדר בשרת',
      recipeImportTooLong: 'הטקסט ארוך מדי. הדבק פחות בכל פעם',
      recipeImportFailed: 'הייבוא נכשל',
      recipeImportAdded: 'נוספו {{count}} מתכונים',
      recipeImportSkipped: '{{count}} דולגו — כבר קיימים',
      recipeReviewTitle: 'אישור מתכונים',
      recipeReviewFound: 'נמצאו {{count}} מתכונים',
      recipeReviewUnmapped: '{{count}} מצרכים לא מזוהים',
      recipeReviewDrop: 'הסר מתכון',
      recipeReviewSave: 'שמור {{count}} מתכונים',
      recipeMethod: 'שיטה',
      recipeMethodNone: 'ללא',
      recipeGlass: 'כוס',
      recipeProducesLabel: 'מייצר מצרך',
      recipeAmount: 'כמות',
      recipeAddIngredient: 'הוסף מצרך',
      recipeOptionalShort: 'רשות',
      recipeGarnishShort: 'קישוט',
      recipeStepsPlaceholder: 'שלב אחד בכל שורה',
      ingredientUnmapped: '— לא מזוהה —',
      ingredientAddNew: '+ הוסף מצרך חדש',
      ingredientNewName: 'שם המצרך',
      recipesSubtitle: '{{count}} מתכונים · {{ingredients}} מצרכים במלאי',
      recipesSearchPlaceholder: 'חפש מתכון או מצרך...',
      recipesFilterAvailability: 'סינון לפי זמינות',
      recipesFilterKind: 'סינון לפי סוג',
      recipesFilter_all: 'הכל',
      recipesFilter_canMake: 'אפשר להכין',
      recipesFilter_missingOne: 'חסר מצרך אחד',
      recipesSectionOwn: 'המתכונים שלי',
      recipesSectionOwnEmpty: 'עוד לא כתבת מתכונים. הוסף מתכון, או העתק אחד מהספרייה כדי להתאים אותו לבר שלך.',
      recipesSectionLibrary: 'ספרייה גלובלית',
      recipesKind_all: 'הכל',
      recipesKind_cocktail: 'קוקטיילים',
      recipesKind_syrup: 'סירופים',
      recipesNone: 'לא נמצאו מתכונים',
      recipesLoadError: 'לא ניתן לטעון את המתכונים',
      recipeCanMake: 'אפשר להכין',
      recipeMissing: 'חסרים {{count}}',
      recipeOptional: '(אופציונלי)',
      recipeGarnish: '(קישוט)',
      recipeInStock: 'במלאי',
      recipeOutOfStock: 'חסר',
      recipeUnknownStock: 'לא מזוהה',
      recipeProduces: 'מייצר {{name}}',
      recipeCopyToMine: 'העתק אליי',
      recipeCopied: 'המתכון הועתק למתכונים שלך',
      recipeAlreadyCopied: 'כבר הועתק אליך',
      recipeCopyError: 'לא ניתן להעתיק את המתכון',
      unit_ml: 'מ״ל',
      unit_cl: 'ס״ל',
      unit_oz: 'אונקיה',
      unit_g: 'גרם',
      unit_dash: 'דאש',
      unit_drop: 'טיפות',
      unit_tsp: 'כפית',
      unit_tbsp: 'כף',
      unit_leaf: 'עלים',
      unit_sprig: 'ענף',
      unit_piece: 'יחידה',
      unit_slice: 'פרוסה',
      unit_rim: 'שפה',
      unit_pinch: 'קורט',
      unit_wedge: 'פלח',
      method_stirred: 'מערבב',
      method_shaken: 'מנוער',
      method_built: 'נבנה בכוס',
      method_blended: 'בבלנדר',
      method_prep: 'הכנה',
      glass_rocks: 'כוס רוקס',
      glass_coupe: 'כוס קופה',
      glass_highball: 'כוס גבוהה',
      glass_flute: 'כוס שמפניה',
      glass_mug: 'ספל',
      glass_wine: 'כוס יין',
      glass_hurricane: 'כוס הוריקן',
      scanProduct: 'סרוק מוצר מתמונה',
      scanScanning: 'מזהה...',
      scanHint: 'צלם או בחר תמונה של הבקבוק — השדות יתמלאו לאישורך',
      scanFilled: 'המוצר זוהה. בדוק את השדות לפני שמירה',
      scanLowConfidence: 'הזיהוי לא ודאי — כדאי לבדוק את כל השדות',
      scanNotADrink: 'בתמונה הזו לא מזוהה מוצר שתייה',
      scanNotConfigured: 'סריקת מוצרים לא מוגדרת בשרת',
      scanTooMany: 'יותר מדי סריקות. נסה שוב בעוד כמה דקות',
      scanFailed: 'הזיהוי נכשל. נסה תמונה ברורה יותר של התווית',
      typeStock: 'טבלת מלאי',
      typeRecipes: 'מתכונים',
      recipesMovedNote: 'המתכונים עברו לאזור המתכונים',
      recipesMovedLink: 'לאזור המתכונים',
      recipesMovePendingTitle: 'המתכונים בדף הזה עדיין בדרך לאזור המתכונים',
      recipesMovePendingNote: 'ההעברה תנסה שוב בטעינה הבאה. אל תמחקו את הדף הזה — המתכונים והתמונות שבו קיימים רק כאן.',
      typeInfo: 'דף מידע',
      typeContacts: 'אנשי קשר',
      typeLinks: 'קישורים',
      typeGallery: 'גלריה',
      // Theme
      theme_light: 'מצב בהיר',
      theme_dark: 'מצב כהה',
      theme_auto: 'לפי המכשיר',
      // Demo
      demoTry: 'כניסה לדמו',
      demoHint: 'בר לדוגמה עם מלאי, הזמנות וספר בר — בלי להירשם.',
      demoLoading: 'מכינים בר לדוגמה…',
      demoReady: 'הדמו מוכן. אפשר לשחק עם הכל.',
      demoError: 'לא הצלחנו להכין דמו. נסו שוב.',
      // Photos
      imageAdd: 'הוספת תמונה',
      imageReplace: 'החלפת תמונה',
      imageRemove: 'הסרה',
      imageUploading: 'מעלה…',
      imageUploadFailed: 'ההעלאה נכשלה. נסו שוב.',
      imageNotAnImage: 'אפשר להעלות תמונות בלבד.',
      imageTooLarge: 'התמונה גדולה מדי גם אחרי הקטנה.',
      productPhoto: 'תמונת מוצר',
      recipePhoto: 'תמונת הקוקטייל',
      themeToggle: 'ערכת צבעים: {{state}}. לחצו להחלפה',
      // Account setup flow
      setupTitle: 'הקמת הבר',
      setupStepOf: 'שלב {{step}} מתוך {{total}}',
      setupLater: 'אחר כך',
      setupSkip: 'דלג',
      setupNext: 'המשך',
      setupFinish: 'סיום',
      setupSaveError: 'השמירה נכשלה. נסו שוב.',
      setupStep_book: 'הספר',
      setupStep_suppliers: 'ספקים',
      setupStep_products: 'מלאי',
      setupStep_team: 'צוות',
      setupTitle_book: 'מה הבר שלכם מנהל?',
      setupHelp_book: 'בחרו את העמודים שיהיו בספר הבר. כל אחד נוצר עם תוכן התחלתי שאפשר לערוך או למחוק.',
      setupTitle_suppliers: 'למי מתקשרים?',
      setupHelp_suppliers: 'הספקים ייכנסו לעמוד אנשי קשר בספר. מספר טלפון שם הופך ללחיץ מהנייד.',
      setupTitle_products: 'המלאי שלכם',
      setupHelp_products: 'אפשר לייבא את המלאי מקובץ אקסל קיים, או להוסיף מוצרים ידנית.',
      setupTitle_team: 'הזמנת הצוות',
      setupHelp_team: 'ברמנים מצטרפים לבר עם קוד ההזמנה הזה.',
      setupProductsHelp: 'ניהול המלאי כולל ייבוא מאקסל שמתאים שורות למוצרים קיימים ויוצר את מה שחסר.',
      setupProductsOpen: 'מעבר לניהול מלאי',
      setupProductsNote: 'אפשר גם לדלג ולחזור לזה מתי שתרצו.',
      setupResumeTitle: 'להשלים את הקמת הבר',
      setupResumeProgress: '{{done}} מתוך {{total}} שלבים הושלמו',
      setupContinue: 'המשך',
      setupDismiss: 'לא תודה',
      // Setup templates
      tplOpening: 'צ׳ק ליסט פתיחה',
      tplOpeningDesc: 'מה עושים כשפותחים את הבר',
      tplClosing: 'צ׳ק ליסט סגירה',
      tplClosingDesc: 'מה עושים בסוף הערב',
      tplHandover: 'העברת משמרת',
      tplHandoverDesc: 'מה מוסרים למשמרת הבאה',
      tplSuppliers: 'ספקים',
      tplSuppliersDesc: 'שמות וטלפונים של מי שמספק לכם',
      tplHouseRules: 'נהלי בית',
      tplHouseRulesDesc: 'איך עובדים אצלכם',
      tplRecipes: 'מתכונים',
      tplRecipesDesc: 'הקוקטיילים של הבית',
      tplStock: 'טבלת מלאי',
      tplStockDesc: 'טבלה חופשית לספירות',
      tplDaily: 'משימות יומיות',
      tplDailyDesc: 'משימה קבועה לכל יום בשבוע',
      // Info pages
      addSection: 'הוסף מקטע',
      sectionHeading: 'כותרת המקטע',
      sectionBody: 'תוכן המקטע',
      noSections: 'אין מקטעים בדף הזה.',
      // Contacts
      addContact: 'הוסף איש קשר',
      contactName: 'שם',
      contactRole: 'תפקיד',
      contactPhone: 'טלפון',
      contactNote: 'הערה',
      noContacts: 'אין אנשי קשר.',
      // Links
      addLink: 'הוסף קישור',
      linkTitle: 'שם הקישור',
      linkUrl: 'כתובת',
      noLinks: 'אין קישורים.',
      // Gallery
      addPhoto: 'הוסף תמונה',
      photoCaption: 'כיתוב',
      photoUrl: 'כתובת תמונה',
      noPhotos: 'אין תמונות.',
      addList: "הוסף רשימה",
      items: 'פריטים',
      selectChecklistPrompt: "בחר צ'קליסט לצפייה",
      addRow: 'הוסף שורה',
      newColumn: 'עמודה חדשה',
      rename: 'שנה שם',
      deleteColumn: 'מחק עמודה',
      emptyCell: '(ריק)',
      emptyClickEdit: '(ריק – לחץ לעריכה)',
      confirmClearBarBook: 'לנקות את כל תוכן ספר הבר? כל התוכן יימחק.',
      // Recipes
      recipesTitle: 'מתכונים',
      loadingRecipes: 'טוען מתכונים...',
      editRecipe: 'ערוך מתכון',
      deleteRecipe: 'מחק מתכון',
      edit: 'ערוך',
      delete: 'מחק',
      ingredients: 'מרכיבים',
      instructions: 'אופן ההכנה',
      saveChanges: 'שמור שינויים',
      cancel: 'ביטול',
      recipeTitleRequired: 'שם המתכון חובה',
      ingredientsPlaceholder: 'מי סוכר\nכוסברה\nמחית פסיפלורה',
      instructionsPlaceholder: 'נערבל את המרכיבים.\nנסנן ונסיים.',
      // Orders list
      ordersListTitle: 'רשימת הזמנות',
      noOrders: 'אין הזמנות',
      dateColumn: 'תאריך',
      filterByDateRange: 'סינון לפי תאריכים',
      dateFrom: 'מתאריך',
      dateTo: 'עד תאריך',
      applyDateFilter: 'הצג',
      clearDateFilter: 'נקה',
      noOrdersInDateRange: 'אין הזמנות בטווח התאריכים שנבחר',
      downloadPdf: 'הורד PDF',
      deleteOrder: 'מחק הזמנה',
      itemColumn: 'פריט',
      quantityColumn: 'כמות',
      itemRemoved: 'הוסר',
      undo: 'החזר',
      removeItemFromOrder: 'הסר פריט מההזמנה',
      noItems: 'אין פריטים',
      confirmDeleteOrder: 'האם אתה בטוח שברצונך למחוק את ההזמנה?',
      orderDeletedSuccess: 'ההזמנה נמחקה בהצלחה',
      orderDeleteError: 'שגיאה במחיקת ההזמנה',
      orderUpdatedSuccess: 'ההזמנה עודכנה בהצלחה',
      orderUpdateError: 'שגיאה בעדכון ההזמנה',
      pdfError: 'שגיאה ביצירת הקובץ',
      noSupplier: 'ללא ספק',
      itemNumber: 'פריט {{n}}',
      // Items management
      itemsManagementTitle: 'ניהול מוצרים',
      noProductsInSystem: 'אין מוצרים במערכת',
      addFirstProduct: 'הוסף מוצר ראשון',
      addFirstRecipe: 'הוסף מתכון ראשון',
      barBookEmpty: 'ספר הבר ריק. לחץ כדי להתחיל.',
      initBarBook: 'אתחל ספר בר',
      category: 'קטגוריה',
      allCategories: 'כל הקטגוריות',
      enterCategory: 'הכנס קטגוריה חדשה',
      supplier: 'ספק',
      allSuppliers: 'כל הספקים',
      stock: 'מלאי',
      all: 'הכל',
      inStock: 'במלאי',
      outOfStock: 'לא במלאי',
      lowStockFilter: 'מלאי נמוך',
      showingProducts: 'מציג {{count}} מתוך {{total}} מוצרים',
      clearFilters: 'נקה פילטרים',
      filters: 'סינון',
      createOrder: 'צור הזמנה ({{n}})',
      importStockExcel: 'ייבוא מלאי מאקסל',
      uploadDocument: 'העלאת מסמך',
      addProduct: 'הוסף מוצר',
      selectOrdersToCreate: 'בחר אילו הזמנות ליצור',
      createOrderModalDesc: 'נבחרו מוצרים להזמנה לפי ספק. סמן את הספקים שאליהם תרצה לשלוח הזמנה.',
      productsCount: '{{n}} מוצרים',
      combinedOrderOption: 'יצירת הזמנה משולבת – איחוד כל המוצרים הנבחרים להזמנה אחת',
      createSelectedOrders: 'צור הזמנות נבחרות',
      importStockTitle: 'ייבוא מלאי מאקסל',
      fileLabel: 'קובץ',
      loading: 'טוען...',
      totalRows: 'סה״כ שורות',
      matchedRows: 'שורות שנמצאה התאמה',
      uniqueItemsToUpdate: 'פריטים ייחודיים שיעודכנו',
      unmatchedRows: 'שורות ללא התאמה',
      createMissingProducts: 'להוסיף גם {{n}} מוצרים שלא קיימים במערכת',
      createMissingHint: 'ייווצרו עם הכמות מהקובץ. נפח ורפי התראה אפשר למלא אחר כך.',
      importCreatedProducts: 'המלאי עודכן ונוספו {{n}} מוצרים חדשים',
      importStaleMatches: '{{n}} שורות דולגו — המוצרים שהותאמו להן כבר לא קיימים',
      showUnmatched: 'הצג שורות ללא התאמה',
      andMore: '... ועוד {{n}}',
      applyStockUpdate: 'החל עדכון מלאי',
      close: 'סגור',
      editProduct: 'ערוך מוצר',
      addNewProduct: 'הוסף מוצר חדש',
      nameHe: 'שם (עברית)',
      nameEn: 'שם (אנגלית)',
      description: 'תיאור',
      selectCategory: 'בחר קטגוריה',
      noCategoriesAvailable: 'אין קטגוריות זמינות',
      categoriesFromProducts: 'נמצאו {{n}} קטגוריות מהמוצרים הקיימים',
      noCategoriesInProducts: 'לא נמצאו קטגוריות במוצרים הקיימים',
      price: 'מחיר',
      stockQuantity: 'כמות במלאי',
      optimalStock: 'כמות אופטימלית למלאי',
      imageUrl: 'תמונה (URL)',
      availableForOrder: 'זמין להזמנה',
      update: 'עדכן',
      save: 'שמור',
      nameColumn: 'שם',
      orderQuantity: 'כמה להזמין',
      actions: 'פעולות',
      noProductsMatchFilters: 'לא נמצאו מוצרים התואמים לפילטרים שנבחרו',
      remove: 'הסר',
      confirmDeleteItem: 'האם אתה בטוח שברצונך למחוק את הפריט?',
      itemDeletedSuccess: 'הפריט נמחק בהצלחה',
      itemDeleteError: 'שגיאה במחיקת הפריט',
      itemSavedSuccess: 'הפריט נוסף בהצלחה',
      itemUpdatedSuccess: 'הפריט עודכן בהצלחה',
      itemSaveError: 'שגיאה בשמירת הפריט',
      optimalUpdated: 'כמות אופטימלית עודכנה',
      optimalUpdateError: 'שגיאה בעדכון הכמות האופטימלית',
      stockUpdated: 'המלאי עודכן',
      stockUpdateError: 'שגיאה בעדכון המלאי',
      noProductsToOrder: 'אין מוצרים להזמנה',
      selectAtLeastOneSupplier: 'נא לבחור לפחות ספק אחד',
      combinedOrderLabel: 'הזמנה משולבת',
      orderCreatedProducts: 'הזמנה נוצרה – {{n}} מוצרים',
      ordersCreatedProducts: 'נוצרו {{c}} הזמנות – {{n}} מוצרים',
      createOrdersError: 'שגיאה ביצירת ההזמנות',
      stockUpdatedSuccess: 'המלאי עודכן בהצלחה',
      readFileError: 'שגיאה בקריאת הקובץ',
      noCategory: 'ללא קטגוריה',
      noValidRows: 'לא נמצאו שורות תקינות. בדוק שיש עמודות שם + מלאי (כמות).',
      // Order page (cart)
      cartTitle: 'עגלת קניות',
      cartEmpty: 'העגלה ריקה',
      supplierLabel: 'ספק',
      quantityLabel: 'כמות',
      totalLabel: 'סה"כ',
      checkoutNow: 'הזמן עכשיו (לפי ספק)',
      clearCart: 'נקה עגלה',
      // Products / menu page
      cannotLoadProducts: 'לא ניתן לטעון מוצרים',
      cannotLoadItemDetails: 'לא ניתן לטעון פרטי מוצר',
      itemNotFound: 'המוצר לא נמצא',
      searchSectionTitle: 'חיפוש',
      categoriesFilterTitle: 'קטגוריות',
      searchProductsPlaceholder: 'חפש מוצרים...',
      clearSearch: 'נקה חיפוש',
      addToCart: 'הוסף לעגלה',
      available: 'זמין',
      unavailable: 'לא זמין',
      allCategoriesFilter: 'הכל',
      paginationPrev: 'קודם',
      paginationNext: 'הבא',
      noItemsFound: 'לא נמצאו מוצרים',
      addToCartButton: 'הוסף לעגלה',
      // Category names (filter buttons – when data has English name)
      category_ALCOHOL: 'אלכוהול',
      category_WINE: 'יין',
      chartTitle: 'כמות הפריטים שהוזמנה מכל ספק בכל יום',
      chartItemsAxis: 'כמות פריטים',
      chartDateAxis: 'תאריך',
      chartItemsSuffix: 'פריטים',
      noOrderDataYet: 'אין עדיין נתוני הזמנות להצגה.',
      // Profile
      profileTitle: 'פרופיל',
      profileFullname: 'שם מלא',
      profileUsername: 'שם משתמש',
      profileRole: 'תפקיד',
      profileMemberSince: 'חבר מאז',
      role_admin: 'מנהל',
      role_manager: 'מנהל משמרת',
      role_bartender: 'ברמן',
      profileNavLink: 'פרופיל',
      profileCompany: 'חברה',
      profileDatabase: 'בסיס נתונים',
      // Signup — company name
      companyNameLabel: 'שם חברה',
      companyNamePlaceholder: 'למשל: bandit',
      companyNameHelp: 'מגדיר את בסיס הנתונים של הבר שלך',
      inviteCodePlaceholder: 'קוד הזמנה (רק בהצטרפות לבר קיים)',
      inviteCodeHelp: 'משאירים ריק כדי ליצור בר חדש. להצטרפות לבר קיים — בקשו קוד מהמנהל.',
      inviteCodeTitle: 'קוד הזמנה לצוות',
      inviteCodeDesc: 'שתפו את הקוד עם ברמנים שמצטרפים לבר. הם יזינו אותו בהרשמה יחד בשם הבר.',
      inviteCodeRegenerate: 'יצירת קוד חדש',
      inviteCodeRegenerated: 'נוצר קוד הזמנה חדש. הקוד הקודם כבר לא תקף.',
      inviteCodeCopied: 'הקוד הועתק',
      inviteCodeCopy: 'העתק',
      inviteCodeError: 'שגיאה בטעינת קוד ההזמנה',
      inviteCodeConfirmRegenerate: 'ליצור קוד חדש? הקוד הנוכחי יפסיק לעבוד.',
      companyNameError: 'שם חברה לא תקין. השתמש באותיות, מספרים ורווחים בלבד.',
      // Profile settings
      settingsTitle: 'הגדרות',
      settingsLanguage: 'שפה',
      // About page
      aboutTagline: 'מערכת ניהול בר חכמה',
      aboutSubtitle: 'ניהול מלאי, הזמנות וספר בר — הכל במקום אחד',
      aboutDescription: 'BarOS נבנה עבור אנשי בר שרוצים לנהל את הבר שלהם בצורה מסודרת ויעילה. ממשק כהה ונקי עם תמיכה מלאה בעברית ואנגלית.',
      aboutFeaturesTitle: 'יכולות',
      aboutInventoryTitle: 'ניהול מלאי',
      aboutInventoryDesc: 'עקוב אחר כל המוצרים, המחירים ורמות המלאי בזמן אמת. קבל התראות כשמלאי מתחיל להיגמר.',
      aboutOrdersTitle: 'הזמנות לספקים',
      aboutOrdersDesc: 'צור הזמנות ישירות מרשימת המלאי. קבץ מוצרים לפי ספק וייצא להזמנה ב-PDF.',
      aboutBarBookTitle: 'ספר הבר',
      aboutBarBookDesc: 'צ׳קליסטים, משימות יומיות לפי ימי שבוע ומתכונים — הכל במקום אחד.',
      aboutDashboardTitle: 'דשבורד',
      aboutDashboardDesc: 'סקירה כללית של פעילות הבר: מוצרים, הזמנות, הכנסות יומיות ותרשים הזמנות לפי ספק.',
      aboutDescription2: 'מבוסס על React, Node.js ו-MongoDB',
      aboutVersion: 'גרסה 1.0',
    },
  },
  en: {
    translation: {
      home: 'Home',
      products: 'Products',
      profile: 'Profile',
      about: 'About',
      more: 'More',
      barBook: 'Bar Book',
      orders: 'Orders',
      itemsManagement: 'Items Management',
      navItemsMgmt: 'Stock',
      cart: 'Cart',
      // Landing page
      landingTagline: 'Smart Bar Management — Inventory, Orders & Bar Book In One Place',
      landingLoginTitle: 'Sign In',
      landingSignupTitle: 'Create Account',
      landingLoginBtn: 'Sign In',
      landingSignupBtn: 'Create Account',
      alreadyMember: 'Already A Member? Sign In',
      newUser: 'New Here? Create An Account',
      fullnamePlaceholder: 'Full Name',
      usernamePlaceholder: 'Username',
      passwordPlaceholder: 'Password',
      welcomeMsg: 'Welcome!',
      loginError: 'Invalid Username Or Password',
      featureInventoryTitle: 'Inventory Management',
      featureInventoryDesc: 'Track Products, Prices And Low-Stock Alerts',
      featureOrdersTitle: 'Supplier Orders',
      featureOrdersDesc: 'Create And Manage Orders Directly From Your Inventory',
      featureBarBookTitle: 'Bar Book',
      featureBarBookDesc: 'Checklists, Daily Tasks And Recipes In One Place',
      featureDashboardTitle: 'Dashboard',
      featureDashboardDesc: 'Real-Time Overview Of Your Bar Activity',
      recipes: 'Recipes',
      dailyTask: 'Daily Task',
      day_0: 'Sunday',
      day_1: 'Monday',
      day_2: 'Tuesday',
      day_3: 'Wednesday',
      day_4: 'Thursday',
      day_5: 'Friday',
      day_6: 'Saturday',
      dayPrefix: '',
      dailyTaskFallback: 'Check Stock And Update The Bar Book',
      supplierOrdersSummaryTitle: 'Orders by Supplier & Product',
      supplierOrdersTotalUnits: 'units total',
      supplierOrdersProduct: 'Product',
      supplierOrdersQty: 'Qty',
      statTotalProducts: 'Total Products',
      statAvailableProducts: 'Available Products',
      statLowStock: 'Low Stock',
      statTotalOrders: 'Total Orders',
      statPendingOrders: 'Pending Orders',
      statTodayRevenue: "Today's Revenue",
      lowStockAlerts: 'Low Stock Alerts',
      stockLabel: 'Stock',
      alertThresholdLabel: 'Alert Min',
      selectItemPrompt: 'Select An Item From The List',
      volumeMlLabel: 'ml Per Bottle',
      volumeMlPlaceholder: 'Bottle Volume In ml (e.g. 700)',
      stockLevel: 'Stock Level',
      totalVolume: 'Total Volume In Stock',
      ml: 'ml',
      litre: 'L',
      suggestedOrder: 'Suggested Order',
      quantityToOrder: 'Quantity To Order',
      updateStock: 'Update Stock',
      decrease: 'Decrease',
      increase: 'Increase',
      unitsInStock: 'Units In Stock',
      unitsByCategory: 'Units By Category',
      unitsOrderedPerDay: 'Units Ordered Per Day',
      unitsOrdered: 'Units Ordered',
      lastNDays: 'Last {{n}} Days',
      allStockOk: 'All Stock Levels Are Fine',
      selectOrderPrompt: 'Select An Order From The List',
      summary: 'Summary',
      totalUnitsLabel: 'Total Units',
      viewAllLowStock: 'View All Products With Low Stock',
      recentOrders: 'Recent Orders',
      viewAll: 'View All',
      orderId: 'Order',
      itemsCount: 'Items',
      status_pending: 'Pending',
      status_completed: 'Completed',
      status_delivered: 'Delivered',
      hello: 'Hello',
      logout: 'Logout',
      switchUser: 'Switch User',
      logoutSuccess: 'See You!',
      loginRequired: 'Please Sign In First',
      toggleLanguage: 'Toggle Language',
      openSidebar: 'Open Menu',
      closeSidebar: 'Close Menu',
      barBookTitle: 'Bar Book',
      tabChecklists: 'Checklists',
      tabPages: 'Stock Pages',
      tabDaily: 'Daily Tasks',
      tabRecipes: 'Recipes',
      editMode: 'Edit',
      exitEditMode: 'Done Editing',
      loadingBarBook: 'Loading Bar Book...',
      pageErrorTitle: 'This Page Stopped Working',
      pageErrorBody: 'The rest of the app is still available from the menu. You can try this page again or reload.',
      pageErrorRetry: 'Try Again',
      pageErrorReload: 'Reload',
      errorLoadBarBook: 'Error Loading Bar Book',
      barBookConflict: 'Another User Updated The Bar Book. Refresh The Page To See The Latest Version.',
      // Bar Book run mode
      newShift: 'New Shift',
      confirmNewShift: 'Clear {{count}} checks and start a new shift?',
      editModeOn: 'Done Editing',
      doneOfTotal: '{{done}} of {{total}}',
      back: 'Back',
      dailyTasksTitle: 'Daily Tasks',
      dailyTasksIntro: 'Daily Tasks Are Performed Every Shift. The Task Is Performed By Day Of The Week.',
      clickToEdit: 'Click To Edit',
      deleteRow: 'Delete Row',
      deleteItem: 'Delete Item',
      deleteDay: 'Delete Day',
      addTask: 'Add Task',
      clearContent: 'Clear Content',
      addPage: 'Add Page',
      pageTitlePlaceholder: 'Page title...',
      confirmDeletePage: 'Delete this page?',
      typeChecklists: 'Checklist',
      typeChecklist: 'List',
      typeTable: 'Table',
      columnPresetsLabel: 'Starting columns (optional)',
      recipeImportTitle: 'Add Recipes',
      recipeImport_write: 'Write',
      recipeImport_paste: 'Paste Text',
      recipeImport_excel: 'From Excel',
      recipeImportPasteHint: 'Paste one recipe or several, in any format. We read the ingredients and measures and show them for you to confirm.',
      recipeImportPastePlaceholder: 'Negroni · 30 ml gin · 30 ml Campari · 30 ml sweet vermouth · Stir with ice and strain...',
      recipeImportExcelHint: 'A file with columns: name, ingredients (one per line), instructions. Matching is done locally - at no cost.',
      recipeImportRead: 'Read Recipes',
      recipeImportReading: 'Reading...',
      recipeImportNoRecipes: 'No Drink Recipe Was Found In This Text',
      recipeImportNoRows: 'No Usable Rows Were Found In The File',
      recipeImportNotConfigured: 'Recipe Import Is Not Configured On The Server',
      recipeImportTooLong: 'That Text Is Too Long. Paste Less At A Time',
      recipeImportFailed: 'The Import Failed',
      recipeImportAdded: '{{count}} Recipes Added',
      recipeImportSkipped: '{{count}} Skipped - Already There',
      recipeReviewTitle: 'Confirm Recipes',
      recipeReviewFound: '{{count}} Recipes Found',
      recipeReviewUnmapped: '{{count}} Ingredients Unrecognised',
      recipeReviewDrop: 'Remove Recipe',
      recipeReviewSave: 'Save {{count}} Recipes',
      recipeMethod: 'Method',
      recipeMethodNone: 'None',
      recipeGlass: 'Glass',
      recipeProducesLabel: 'Makes Ingredient',
      recipeAmount: 'Amount',
      recipeAddIngredient: 'Add Ingredient',
      recipeOptionalShort: 'Optional',
      recipeGarnishShort: 'Garnish',
      recipeStepsPlaceholder: 'One Step Per Line',
      ingredientUnmapped: '- Unrecognised -',
      ingredientAddNew: '+ Add A New Ingredient',
      ingredientNewName: 'Ingredient Name',
      recipesSubtitle: '{{count}} Recipes · {{ingredients}} Ingredients In Stock',
      recipesSearchPlaceholder: 'Search A Recipe Or An Ingredient...',
      recipesFilterAvailability: 'Filter By Availability',
      recipesFilterKind: 'Filter By Kind',
      recipesFilter_all: 'All',
      recipesFilter_canMake: 'Can Make',
      recipesFilter_missingOne: 'One Away',
      recipesSectionOwn: 'My Recipes',
      recipesSectionOwnEmpty: 'No recipes of your own yet. Add one, or copy a recipe from the library to make it yours.',
      recipesSectionLibrary: 'Global Library',
      recipesKind_all: 'All',
      recipesKind_cocktail: 'Cocktails',
      recipesKind_syrup: 'Syrups',
      recipesNone: 'No Recipes Found',
      recipesLoadError: 'Cannot Load Recipes',
      recipeCanMake: 'Can Make',
      recipeMissing: 'Missing {{count}}',
      recipeOptional: '(Optional)',
      recipeGarnish: '(Garnish)',
      recipeInStock: 'In Stock',
      recipeOutOfStock: 'Missing',
      recipeUnknownStock: 'Unrecognised',
      recipeProduces: 'Makes {{name}}',
      recipeCopyToMine: 'Copy To Mine',
      recipeCopied: 'Recipe Copied To Your Recipes',
      recipeAlreadyCopied: 'Already Copied To Yours',
      recipeCopyError: 'Could Not Copy The Recipe',
      unit_ml: 'ml',
      unit_cl: 'cl',
      unit_oz: 'oz',
      unit_g: 'g',
      unit_dash: 'dash',
      unit_drop: 'drops',
      unit_tsp: 'tsp',
      unit_tbsp: 'tbsp',
      unit_leaf: 'leaves',
      unit_sprig: 'sprig',
      unit_piece: 'piece',
      unit_slice: 'slice',
      unit_rim: 'rim',
      unit_pinch: 'pinch',
      unit_wedge: 'wedge',
      method_stirred: 'Stirred',
      method_shaken: 'Shaken',
      method_built: 'Built In Glass',
      method_blended: 'Blended',
      method_prep: 'Preparation',
      glass_rocks: 'Rocks Glass',
      glass_coupe: 'Coupe',
      glass_highball: 'Highball',
      glass_flute: 'Flute',
      glass_mug: 'Mug',
      glass_wine: 'Wine Glass',
      glass_hurricane: 'Hurricane',
      scanProduct: 'Scan Product From Photo',
      scanScanning: 'Identifying...',
      scanHint: 'Photograph the bottle or pick a picture - the fields fill in for you to confirm',
      scanFilled: 'Product identified. Check the fields before saving',
      scanLowConfidence: 'Identification is uncertain - check every field',
      scanNotADrink: 'No drink product is recognised in this photograph',
      scanNotConfigured: 'Product scanning is not configured on the server',
      scanTooMany: 'Too many scans. Try again in a few minutes',
      scanFailed: 'Identification failed. Try a clearer photograph of the label',
      typeStock: 'Stock Table',
      typeRecipes: 'Recipes',
      recipesMovedNote: 'Recipes have moved to the Recipes section',
      recipesMovedLink: 'Go to Recipes',
      recipesMovePendingTitle: 'The recipes on this page are still being moved to the Recipes section',
      recipesMovePendingNote: 'The move will be retried on the next load. Do not delete this page — its recipes and photos exist only here.',
      typeInfo: 'Info Page',
      typeContacts: 'Contacts',
      typeLinks: 'Links',
      typeGallery: 'Gallery',
      // Theme
      theme_light: 'Light Mode',
      theme_dark: 'Dark Mode',
      theme_auto: 'Match Device',
      // Demo
      demoTry: 'Try The Demo',
      demoHint: 'A sample bar with stock, orders and a bar book — no signup.',
      demoLoading: 'Pouring A Sample Bar…',
      demoReady: 'Demo Ready. Change Anything You Like.',
      demoError: 'Could Not Start A Demo. Please Try Again.',
      // Photos
      imageAdd: 'Add Photo',
      imageReplace: 'Replace Photo',
      imageRemove: 'Remove',
      imageUploading: 'Uploading…',
      imageUploadFailed: 'Upload Failed. Please Try Again.',
      imageNotAnImage: 'Images Only, Please.',
      imageTooLarge: 'That Photo Is Still Too Large After Shrinking.',
      productPhoto: 'Product Photo',
      recipePhoto: 'Cocktail Photo',
      themeToggle: 'Theme: {{state}}. Click To Change',
      // Account setup flow
      setupTitle: 'Set Up Your Bar',
      setupStepOf: 'Step {{step}} Of {{total}}',
      setupLater: 'Later',
      setupSkip: 'Skip',
      setupNext: 'Continue',
      setupFinish: 'Finish',
      setupSaveError: 'That did not save. Try again.',
      setupStep_book: 'Book',
      setupStep_suppliers: 'Suppliers',
      setupStep_products: 'Stock',
      setupStep_team: 'Team',
      setupTitle_book: 'What Does Your Bar Keep?',
      setupHelp_book: 'Pick the pages your bar book will have. Each one arrives with a starting list you can edit or delete.',
      setupTitle_suppliers: 'Who Do You Call?',
      setupHelp_suppliers: 'These become a contacts page in your book. A number there is tap-to-call on a phone.',
      setupTitle_products: 'Your Stock',
      setupHelp_products: 'Import your stock from a spreadsheet you already have, or add products by hand.',
      setupTitle_team: 'Invite Your Team',
      setupHelp_team: 'Bartenders join your bar with this invite code.',
      setupProductsHelp: 'Stock management has an Excel import that matches rows to existing products and creates the ones it cannot match.',
      setupProductsOpen: 'Open Stock Management',
      setupProductsNote: 'You can skip this and come back to it whenever you like.',
      setupResumeTitle: 'Finish Setting Up Your Bar',
      setupResumeProgress: '{{done}} Of {{total}} Steps Done',
      setupContinue: 'Continue',
      setupDismiss: 'No Thanks',
      // Setup templates
      tplOpening: 'Opening Checklist',
      tplOpeningDesc: 'What you do when the bar opens',
      tplClosing: 'Closing Checklist',
      tplClosingDesc: 'What you do at the end of the night',
      tplHandover: 'Shift Handover',
      tplHandoverDesc: 'What you hand to the next shift',
      tplSuppliers: 'Suppliers',
      tplSuppliersDesc: 'Names and numbers of who supplies you',
      tplHouseRules: 'House Rules',
      tplHouseRulesDesc: 'How things are done at your bar',
      tplRecipes: 'Recipes',
      tplRecipesDesc: 'Your house cocktails',
      tplStock: 'Stock Table',
      tplStockDesc: 'A free table for counts',
      tplDaily: 'Daily Tasks',
      tplDailyDesc: 'A standing task for each day of the week',
      // Info pages
      addSection: 'Add Section',
      sectionHeading: 'Section Heading',
      sectionBody: 'Section Text',
      noSections: 'This Page Has No Sections Yet.',
      // Contacts
      addContact: 'Add Contact',
      contactName: 'Name',
      contactRole: 'Role',
      contactPhone: 'Phone',
      contactNote: 'Note',
      noContacts: 'No Contacts Yet.',
      // Links
      addLink: 'Add Link',
      linkTitle: 'Link Name',
      linkUrl: 'Address',
      noLinks: 'No Links Yet.',
      // Gallery
      addPhoto: 'Add Photo',
      photoCaption: 'Caption',
      photoUrl: 'Image Address',
      noPhotos: 'No Photos Yet.',
      addList: 'Add List',
      items: 'items',
      selectChecklistPrompt: 'Select a checklist to view',
      addRow: 'Add Row',
      newColumn: 'New Column',
      rename: 'Rename',
      deleteColumn: 'Delete Column',
      emptyCell: '(Empty)',
      emptyClickEdit: '(Empty – Click To Edit)',
      confirmClearBarBook: 'Clear All Bar Book Content? All Content Will Be Deleted.',
      recipesTitle: 'Recipes',
      loadingRecipes: 'Loading Recipes...',
      editRecipe: 'Edit Recipe',
      deleteRecipe: 'Delete Recipe',
      edit: 'Edit',
      delete: 'Delete',
      ingredients: 'Ingredients',
      instructions: 'Instructions',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      recipeTitleRequired: 'Recipe Name Is Required',
      ingredientsPlaceholder: 'Sugar water\nCoriander\nPassion fruit puree',
      instructionsPlaceholder: 'Mix the ingredients.\nStrain and finish.',
      // Orders list
      ordersListTitle: 'Orders List',
      noOrders: 'No Orders',
      dateColumn: 'Date',
      filterByDateRange: 'Filter by date range',
      dateFrom: 'From',
      dateTo: 'To',
      applyDateFilter: 'Show',
      clearDateFilter: 'Clear',
      noOrdersInDateRange: 'No orders in selected date range',
      downloadPdf: 'Download PDF',
      deleteOrder: 'Delete Order',
      itemColumn: 'Item',
      quantityColumn: 'Quantity',
      itemRemoved: 'Removed',
      undo: 'Undo',
      removeItemFromOrder: 'Remove Item From Order',
      noItems: 'No Items',
      confirmDeleteOrder: 'Are You Sure You Want To Delete This Order?',
      orderDeletedSuccess: 'Order Deleted Successfully',
      orderDeleteError: 'Error Deleting Order',
      orderUpdatedSuccess: 'Order Updated Successfully',
      orderUpdateError: 'Error Updating Order',
      pdfError: 'Error Creating File',
      noSupplier: 'No Supplier',
      itemNumber: 'Item {{n}}',
      // Items management
      itemsManagementTitle: 'Items Management',
      noProductsInSystem: 'No Products In The System',
      addFirstProduct: 'Add Your First Product',
      addFirstRecipe: 'Add Your First Recipe',
      barBookEmpty: 'Bar Book Is Empty. Click To Get Started.',
      initBarBook: 'Initialize Bar Book',
      category: 'Category',
      allCategories: 'All Categories',
      enterCategory: 'Enter New Category',
      supplier: 'Supplier',
      allSuppliers: 'All Suppliers',
      stock: 'Stock',
      all: 'All',
      inStock: 'In Stock',
      outOfStock: 'Out Of Stock',
      lowStockFilter: 'Low Stock',
      showingProducts: 'Showing {{count}} Of {{total}} Products',
      clearFilters: 'Clear Filters',
      filters: 'Filters',
      createOrder: 'Create Order ({{n}})',
      importStockExcel: 'Import Stock From Excel',
      uploadDocument: 'Upload Document',
      addProduct: 'Add Product',
      selectOrdersToCreate: 'Select Which Orders To Create',
      createOrderModalDesc: 'Products To Order Are Grouped By Supplier. Check The Suppliers You Want To Send An Order To.',
      productsCount: '{{n}} Products',
      combinedOrderOption: 'Create Combined Order – Merge All Selected Products Into One Order',
      createSelectedOrders: 'Create Selected Orders',
      importStockTitle: 'Import Stock From Excel',
      fileLabel: 'File',
      loading: 'Loading...',
      totalRows: 'Total Rows',
      matchedRows: 'Matched Rows',
      uniqueItemsToUpdate: 'Unique Items To Update',
      unmatchedRows: 'Unmatched Rows',
      createMissingProducts: 'Also add {{n}} products that are not in the system',
      createMissingHint: 'They will be created with the quantity from the file. Volume and thresholds can be filled in afterwards.',
      importCreatedProducts: 'Stock updated and {{n}} new products added',
      importStaleMatches: '{{n}} rows were skipped — the products they matched no longer exist',
      showUnmatched: 'Show Unmatched Rows',
      andMore: '... And {{n}} More',
      applyStockUpdate: 'Apply Stock Update',
      close: 'Close',
      editProduct: 'Edit Product',
      addNewProduct: 'Add New Product',
      nameHe: 'Name (Hebrew)',
      nameEn: 'Name (English)',
      description: 'Description',
      selectCategory: 'Select Category',
      noCategoriesAvailable: 'No Categories Available',
      categoriesFromProducts: 'Found {{n}} Categories From Existing Products',
      noCategoriesInProducts: 'No Categories Found In Existing Products',
      price: 'Price',
      stockQuantity: 'Stock',
      optimalStock: 'Optimal',
      imageUrl: 'Image (URL)',
      availableForOrder: 'Available For Order',
      update: 'Update',
      save: 'Save',
      nameColumn: 'Name',
      orderQuantity: 'Order Qty',
      actions: 'Actions',
      noProductsMatchFilters: 'No Products Match The Selected Filters',
      remove: 'Remove',
      confirmDeleteItem: 'Are You Sure You Want To Delete This Item?',
      itemDeletedSuccess: 'Item Deleted Successfully',
      itemDeleteError: 'Error Deleting Item',
      itemSavedSuccess: 'Item Added Successfully',
      itemUpdatedSuccess: 'Item Updated Successfully',
      itemSaveError: 'Error Saving Item',
      optimalUpdated: 'Optimal Quantity Updated',
      optimalUpdateError: 'Error Updating Optimal Quantity',
      stockUpdated: 'Stock Updated',
      stockUpdateError: 'Error Updating Stock',
      noProductsToOrder: 'No Products To Order',
      selectAtLeastOneSupplier: 'Please Select At Least One Supplier',
      combinedOrderLabel: 'Combined Order',
      orderCreatedProducts: 'Order Created – {{n}} Products',
      ordersCreatedProducts: '{{c}} Orders Created – {{n}} Products',
      createOrdersError: 'Error Creating Orders',
      stockUpdatedSuccess: 'Stock Updated Successfully',
      readFileError: 'Error Reading File',
      noCategory: 'No Category',
      noValidRows: 'No Valid Rows Found. Make Sure There Are Name + Stock (Quantity) Columns.',
      // Order page (cart)
      cartTitle: 'Shopping Cart',
      cartEmpty: 'Cart Is Empty',
      supplierLabel: 'Supplier',
      quantityLabel: 'Quantity',
      totalLabel: 'Total',
      checkoutNow: 'Checkout Now (By Supplier)',
      clearCart: 'Clear Cart',
      // Products / menu page
      cannotLoadProducts: 'Cannot Load Products',
      cannotLoadItemDetails: 'Cannot Load Item Details',
      itemNotFound: 'Item Not Found',
      searchSectionTitle: 'Search',
      categoriesFilterTitle: 'Categories',
      searchProductsPlaceholder: 'Search Products...',
      clearSearch: 'Clear Search',
      addToCart: 'Add To Cart',
      available: 'Available',
      unavailable: 'Unavailable',
      allCategoriesFilter: 'All',
      paginationPrev: 'Previous',
      paginationNext: 'Next',
      noItemsFound: 'No Items Found',
      addToCartButton: 'Add To Cart',
      category_ALCOHOL: 'Alcohol',
      category_WINE: 'Wine',
      chartTitle: 'Items Ordered Per Supplier Per Day',
      chartItemsAxis: 'Item Count',
      chartDateAxis: 'Date',
      chartItemsSuffix: 'Items',
      noOrderDataYet: 'No Order Data To Display Yet.',
      // Profile
      profileTitle: 'Profile',
      profileFullname: 'Full Name',
      profileUsername: 'Username',
      profileRole: 'Role',
      profileMemberSince: 'Member Since',
      role_admin: 'Admin',
      role_manager: 'Shift Manager',
      role_bartender: 'Bartender',
      profileNavLink: 'Profile',
      profileCompany: 'Company',
      profileDatabase: 'Database',
      // Signup — company name
      companyNameLabel: 'Company Name',
      companyNamePlaceholder: 'e.g. Bandit',
      companyNameHelp: 'Sets The Database Name For Your Bar',
      inviteCodePlaceholder: 'Invite Code (Only When Joining An Existing Bar)',
      inviteCodeHelp: 'Leave Empty To Create A New Bar. To Join An Existing One, Ask Its Admin For A Code.',
      inviteCodeTitle: 'Team Invite Code',
      inviteCodeDesc: 'Share This Code With Bartenders Joining Your Bar. They Enter It At Signup Along With The Bar Name.',
      inviteCodeRegenerate: 'Generate New Code',
      inviteCodeRegenerated: 'A New Invite Code Was Generated. The Previous One No Longer Works.',
      inviteCodeCopied: 'Code Copied',
      inviteCodeCopy: 'Copy',
      inviteCodeError: 'Error Loading Invite Code',
      inviteCodeConfirmRegenerate: 'Generate A New Code? The Current One Will Stop Working.',
      companyNameError: 'Invalid Company Name. Use Letters, Numbers And Spaces Only.',
      // Profile settings
      settingsTitle: 'Settings',
      settingsLanguage: 'Language',
      // About page
      aboutTagline: 'Smart Bar Management',
      aboutSubtitle: 'Inventory, Orders And Bar Book — All In One Place',
      aboutDescription: 'BarOS Is Built For Bar Professionals Who Want To Manage Their Bar In An Organized, Efficient Way. Clean Dark Interface With Full Hebrew And English Support.',
      aboutFeaturesTitle: 'Features',
      aboutInventoryTitle: 'Inventory Management',
      aboutInventoryDesc: 'Track All Products, Prices And Stock Levels In Real Time. Get Alerts When Stock Runs Low.',
      aboutOrdersTitle: 'Supplier Orders',
      aboutOrdersDesc: 'Create Orders Directly From Your Inventory List. Group Items By Supplier And Export To PDF.',
      aboutBarBookTitle: 'Bar Book',
      aboutBarBookDesc: 'Checklists, Daily Tasks By Day Of The Week, And Recipes — All In One Place.',
      aboutDashboardTitle: 'Dashboard',
      aboutDashboardDesc: 'Overview Of Bar Activity: Products, Orders, Daily Revenue And Orders Chart By Supplier.',
      aboutDescription2: 'Built With React, Node.js And MongoDB',
      aboutVersion: 'Version 1.0',
    },
  },
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    supportedLngs: ['he', 'en'],
    lng: 'en',
    debug: false,
    interpolation: {
      escapeValue: false,
    },
  })

function setDocumentLanguage(lng) {
  const lang = lng || i18n.language
  if (document.documentElement) {
    document.documentElement.lang = lang
    document.documentElement.setAttribute('dir', lang === 'he' ? 'rtl' : 'ltr')
  }
}
setDocumentLanguage()
i18n.on('languageChanged', setDocumentLanguage)

export default i18n
