import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const resources = {
  he: {
    translation: {
      home: 'בית',
      products: 'מוצרים',
      profile: 'פרופיל',
      about: 'אודות',
      barBook: 'ספר בר',
      orders: 'הזמנות',
      itemsManagement: 'ניהול מוצרים',
      cart: 'עגלת קניות',
      recipes: 'מתכונים',
      // Landing page
      landingTagline: 'מערכת ניהול בר חכמה לשמירת סדר, מלאי והזמנות',
      landingLoginTitle: 'כניסה למערכת',
      landingSignupTitle: 'יצירת חשבון חדש',
      landingLoginBtn: 'כניסה',
      landingSignupBtn: 'יצירת חשבון',
      alreadyMember: 'כבר רשום? לחץ להתחברות',
      newUser: 'משתמש חדש? לחץ להירשם',
      fullnamePlaceholder: 'שם מלא',
      usernamePlaceholder: 'שם משתמש',
      passwordPlaceholder: 'סיסמה',
      welcomeMsg: 'ברוך הבא!',
      loginError: 'שם משתמש או סיסמה שגויים',
      featureInventoryTitle: 'ניהול מלאי',
      featureInventoryDesc: 'עקוב אחר מוצרים, מחירים והתראות מלאי נמוך',
      featureOrdersTitle: 'הזמנות לספקים',
      featureOrdersDesc: 'צור ונהל הזמנות ישירות מרשימת המלאי',
      featureBarBookTitle: 'ספר בר',
      featureBarBookDesc: 'צ׳קליסטים, משימות יומיות ומתכונים במקום אחד',
      featureDashboardTitle: 'דשבורד',
      featureDashboardDesc: 'סקירה כללית של הפעילות בזמן אמת',
      // Home page
      dailyTask: 'משימה יומית',
      day_0: 'ראשון',
      day_1: 'שני',
      day_2: 'שלישי',
      day_3: 'רביעי',
      day_4: 'חמישי',
      day_5: 'שישי',
      day_6: 'שבת',
      dayPrefix: 'יום',
      dailyTaskFallback: 'בדוק מלאי ועדכן את ספר הבר',
      supplierOrdersSummaryTitle: 'כמות הזמנות לפי ספק ומוצר',
      supplierOrdersTotalUnits: 'יחידות בסה"כ',
      supplierOrdersProduct: 'מוצר',
      supplierOrdersQty: 'כמות',
      statTotalProducts: 'סה"כ מוצרים',
      statAvailableProducts: 'מוצרים זמינים',
      statLowStock: 'מלאי נמוך',
      statTotalOrders: 'סה"כ הזמנות',
      statPendingOrders: 'הזמנות ממתינות',
      statTodayRevenue: 'הכנסות היום',
      lowStockAlerts: 'התראות מלאי נמוך',
      stockLabel: 'מלאי',
      alertThresholdLabel: 'רף התראה',
      viewAllLowStock: 'צפה בכל המוצרים עם מלאי נמוך',
      recentOrders: 'הזמנות אחרונות',
      viewAll: 'צפה בהכל',
      orderId: 'הזמנה',
      itemsCount: 'פריטים',
      status_pending: 'ממתין',
      status_completed: 'הושלם',
      status_delivered: 'נמסר',
      // Header
      hello: 'שלום',
      logout: 'התנתק',
      switchUser: 'החלף משתמש',
      logoutSuccess: 'להתראות!',
      loginRequired: 'יש להתחבר תחילה',
      toggleLanguage: 'החלף שפה',
      openSidebar: 'פתח תפריט',
      closeSidebar: 'סגור תפריט',
      // Bar Book
      barBookTitle: 'ספר בר',
      tabChecklists: 'צ\'קליסטים',
      tabPages: 'דפי מלאים',
      tabDaily: 'משימות יומיות',
      tabRecipes: 'מתכונים',
      editMode: 'עריכה',
      exitEditMode: 'סיום עריכה',
      loadingBarBook: 'טוען ספר בר...',
      errorLoadBarBook: 'שגיאה בטעינת ספר הבר',
      dailyTasksTitle: 'משימות יומיות',
      dailyTasksIntro: 'משימות יומיות מתבצעות בכל משמרת. המשימה מתבצעת לפי יום בשבוע.',
      dayColumn: 'יום',
      dailyTaskColumn: 'משימה יומית',
      clickToEdit: 'לחץ לעריכה',
      deleteRow: 'מחק שורה',
      deleteItem: 'מחק משימה',
      deleteDay: 'מחק יום',
      addTask: 'הוסף משימה',
      addDay: 'הוסף יום',
      clearContent: 'נקה תוכן',
      addPage: 'הוסף עמוד',
      pageTitlePlaceholder: 'שם העמוד...',
      confirmDeletePage: 'למחוק את העמוד הזה?',
      typeChecklists: "צ'קליסטים",
      typeChecklist: "צ'קליסט",
      typeDaily: 'משימות יומיות',
      typeStock: 'טבלת מלאי',
      typeRecipes: 'מתכונים',
      addList: "הוסף רשימה",
      items: 'פריטים',
      selectChecklistPrompt: "בחר צ'קליסט לצפייה",
      addRow: 'הוסף שורה',
      newColumn: 'עמודה חדשה',
      rename: 'שנה שם',
      deleteColumn: 'מחק עמודה',
      newDay: 'יום חדש',
      dailyTaskPlaceholder: 'כתוב כאן את כל המשימות ליום זה...',
      emptyCell: '(ריק)',
      emptyClickEdit: '(ריק – לחץ לעריכה)',
      confirmClearBarBook: 'לנקות את כל תוכן ספר הבר? כל התוכן יימחק.',
      // Recipes
      recipesTitle: 'מתכונים',
      addRecipe: 'הוסף מתכון',
      loadingRecipes: 'טוען מתכונים...',
      noRecipes: 'אין מתכונים. הוסף מתכון ראשון.',
      selectRecipePrompt: 'בחר מתכון לצפייה',
      editRecipe: 'ערוך מתכון',
      deleteRecipe: 'מחק מתכון',
      edit: 'ערוך',
      delete: 'מחק',
      ingredients: 'מרכיבים',
      instructions: 'אופן ההכנה',
      editingRecipe: 'עריכת מתכון',
      addingRecipe: 'הוספת מתכון',
      recipeNameLabel: 'שם המתכון',
      recipeNamePlaceholder: 'למשל: סירופ קינמון',
      ingredientsLabel: 'מרכיבים (שורה אחת לכל מרכיב)',
      instructionsLabel: 'אופן ההכנה (שורה אחת לכל שלב)',
      saveChanges: 'שמור שינויים',
      cancel: 'ביטול',
      recipeTitleRequired: 'שם המתכון חובה',
      minOneIngredient: 'יש להזין לפחות מרכיב אחד',
      minOneStep: 'יש להזין לפחות שלב אחד',
      confirmDeleteRecipe: 'למחוק את המתכון',
      ingredientsPlaceholder: 'מי סוכר\nכוסברה\nמחית פסיפלורה',
      instructionsPlaceholder: 'נערבל את המרכיבים.\nנסנן ונסיים.',
      // Orders list
      ordersListTitle: 'רשימת הזמנות',
      noOrders: 'אין הזמנות',
      dateColumn: 'תאריך',
      filterByDateRange: 'סינון לפי תאריכים',
      dateFrom: 'מתאריך',
      dateTo: 'עד תאריך',
      applyDateFilter: 'הצג',
      clearDateFilter: 'נקה',
      noOrdersInDateRange: 'אין הזמנות בטווח התאריכים שנבחר',
      downloadPdf: 'הורד PDF',
      deleteOrder: 'מחק הזמנה',
      itemColumn: 'פריט',
      quantityColumn: 'כמות',
      itemRemoved: 'הוסר',
      undo: 'החזר',
      removeItemFromOrder: 'הסר פריט מההזמנה',
      noItems: 'אין פריטים',
      confirmDeleteOrder: 'האם אתה בטוח שברצונך למחוק את ההזמנה?',
      orderDeletedSuccess: 'ההזמנה נמחקה בהצלחה',
      orderDeleteError: 'שגיאה במחיקת ההזמנה',
      orderUpdatedSuccess: 'ההזמנה עודכנה בהצלחה',
      orderUpdateError: 'שגיאה בעדכון ההזמנה',
      pdfError: 'שגיאה ביצירת הקובץ',
      noSupplier: 'ללא ספק',
      itemNumber: 'פריט {{n}}',
      // Items management
      itemsManagementTitle: 'ניהול מוצרים',
      noProductsInSystem: 'אין מוצרים במערכת',
      addFirstProduct: 'הוסף מוצר ראשון',
      addFirstRecipe: 'הוסף מתכון ראשון',
      barBookEmpty: 'ספר הבר ריק. לחץ כדי להתחיל.',
      initBarBook: 'אתחל ספר בר',
      category: 'קטגוריה',
      allCategories: 'כל הקטגוריות',
      enterCategory: 'הכנס קטגוריה חדשה',
      supplier: 'ספק',
      allSuppliers: 'כל הספקים',
      stock: 'מלאי',
      all: 'הכל',
      inStock: 'במלאי',
      outOfStock: 'לא במלאי',
      lowStockFilter: 'מלאי נמוך',
      showingProducts: 'מציג {{count}} מתוך {{total}} מוצרים',
      clearFilters: 'נקה פילטרים',
      createOrder: 'צור הזמנה ({{n}})',
      importStockExcel: 'ייבוא מלאי מאקסל',
      uploadDocument: 'העלאת מסמך',
      addProduct: 'הוסף מוצר',
      selectOrdersToCreate: 'בחר אילו הזמנות ליצור',
      createOrderModalDesc: 'נבחרו מוצרים להזמנה לפי ספק. סמן את הספקים שאליהם תרצה לשלוח הזמנה.',
      productsCount: '{{n}} מוצרים',
      combinedOrderOption: 'יצירת הזמנה משולבת – איחוד כל המוצרים הנבחרים להזמנה אחת',
      createSelectedOrders: 'צור הזמנות נבחרות',
      importStockTitle: 'ייבוא מלאי מאקסל',
      fileLabel: 'קובץ',
      loading: 'טוען...',
      totalRows: 'סה״כ שורות',
      matchedRows: 'שורות שנמצאה התאמה',
      uniqueItemsToUpdate: 'פריטים ייחודיים שיעודכנו',
      unmatchedRows: 'שורות ללא התאמה',
      showUnmatched: 'הצג שורות ללא התאמה',
      andMore: '... ועוד {{n}}',
      applyStockUpdate: 'החל עדכון מלאי',
      close: 'סגור',
      editProduct: 'ערוך מוצר',
      addNewProduct: 'הוסף מוצר חדש',
      nameHe: 'שם (עברית)',
      nameEn: 'שם (אנגלית)',
      description: 'תיאור',
      selectCategory: 'בחר קטגוריה',
      noCategoriesAvailable: 'אין קטגוריות זמינות',
      categoriesFromProducts: 'נמצאו {{n}} קטגוריות מהמוצרים הקיימים',
      noCategoriesInProducts: 'לא נמצאו קטגוריות במוצרים הקיימים',
      price: 'מחיר',
      stockQuantity: 'כמות במלאי',
      optimalStock: 'כמות אופטימלית למלאי',
      imageUrl: 'תמונה (URL)',
      availableForOrder: 'זמין להזמנה',
      update: 'עדכן',
      save: 'שמור',
      nameColumn: 'שם',
      orderQuantity: 'כמה להזמין',
      actions: 'פעולות',
      noProductsMatchFilters: 'לא נמצאו מוצרים התואמים לפילטרים שנבחרו',
      remove: 'הסר',
      confirmDeleteItem: 'האם אתה בטוח שברצונך למחוק את הפריט?',
      itemDeletedSuccess: 'הפריט נמחק בהצלחה',
      itemDeleteError: 'שגיאה במחיקת הפריט',
      itemSavedSuccess: 'הפריט נוסף בהצלחה',
      itemUpdatedSuccess: 'הפריט עודכן בהצלחה',
      itemSaveError: 'שגיאה בשמירת הפריט',
      optimalUpdated: 'כמות אופטימלית עודכנה',
      optimalUpdateError: 'שגיאה בעדכון הכמות האופטימלית',
      stockUpdated: 'המלאי עודכן',
      stockUpdateError: 'שגיאה בעדכון המלאי',
      noProductsToOrder: 'אין מוצרים להזמנה',
      selectAtLeastOneSupplier: 'נא לבחור לפחות ספק אחד',
      combinedOrderLabel: 'הזמנה משולבת',
      orderCreatedProducts: 'הזמנה נוצרה – {{n}} מוצרים',
      ordersCreatedProducts: 'נוצרו {{c}} הזמנות – {{n}} מוצרים',
      createOrdersError: 'שגיאה ביצירת ההזמנות',
      stockUpdatedSuccess: 'המלאי עודכן בהצלחה',
      stockUpdateError: 'שגיאה בעדכון המלאי',
      readFileError: 'שגיאה בקריאת הקובץ',
      noCategory: 'ללא קטגוריה',
      noValidRows: 'לא נמצאו שורות תקינות. בדוק שיש עמודות שם + מלאי (כמות).',
      // Order page (cart)
      cartTitle: 'עגלת קניות',
      cartEmpty: 'העגלה ריקה',
      supplierLabel: 'ספק',
      quantityLabel: 'כמות',
      totalLabel: 'סה"כ',
      checkoutNow: 'הזמן עכשיו (לפי ספק)',
      clearCart: 'נקה עגלה',
      // Products / menu page
      cannotLoadProducts: 'לא ניתן לטעון מוצרים',
      cannotLoadItemDetails: 'לא ניתן לטעון פרטי מוצר',
      itemNotFound: 'המוצר לא נמצא',
      searchSectionTitle: 'חיפוש',
      categoriesFilterTitle: 'קטגוריות',
      searchProductsPlaceholder: 'חפש מוצרים...',
      clearSearch: 'נקה חיפוש',
      addToCart: 'הוסף לעגלה',
      available: 'זמין',
      unavailable: 'לא זמין',
      allCategoriesFilter: 'הכל',
      paginationPrev: 'קודם',
      paginationNext: 'הבא',
      noItemsFound: 'לא נמצאו מוצרים',
      addToCartButton: 'הוסף לעגלה',
      // Category names (filter buttons – when data has English name)
      category_ALCOHOL: 'אלכוהול',
      category_WINE: 'יין',
      chartTitle: 'כמות הפריטים שהוזמנה מכל ספק בכל יום',
      chartItemsAxis: 'כמות פריטים',
      chartDateAxis: 'תאריך',
      chartItemsSuffix: 'פריטים',
      noOrderDataYet: 'אין עדיין נתוני הזמנות להצגה.',
      // Profile
      profileTitle: 'פרופיל',
      profileFullname: 'שם מלא',
      profileUsername: 'שם משתמש',
      profileRole: 'תפקיד',
      profileMemberSince: 'חבר מאז',
      role_admin: 'מנהל',
      role_manager: 'מנהל משמרת',
      role_bartender: 'ברמן',
      profileNavLink: 'פרופיל',
      profileCompany: 'חברה',
      profileDatabase: 'בסיס נתונים',
      // Signup — company name
      companyNameLabel: 'שם חברה',
      companyNamePlaceholder: 'למשל: bandit',
      companyNameHelp: 'מגדיר את בסיס הנתונים של הבר שלך',
      companyNameError: 'שם חברה לא תקין. השתמש באותיות, מספרים ורווחים בלבד.',
      // Profile settings
      settingsTitle: 'הגדרות',
      settingsLanguage: 'שפה',
      // About page
      aboutTagline: 'מערכת ניהול בר חכמה',
      aboutSubtitle: 'ניהול מלאי, הזמנות וספר בר — הכל במקום אחד',
      aboutDescription: 'BarOS נבנה עבור אנשי בר שרוצים לנהל את הבר שלהם בצורה מסודרת ויעילה. ממשק כהה ונקי עם תמיכה מלאה בעברית ואנגלית.',
      aboutFeaturesTitle: 'יכולות',
      aboutInventoryTitle: 'ניהול מלאי',
      aboutInventoryDesc: 'עקוב אחר כל המוצרים, המחירים ורמות המלאי בזמן אמת. קבל התראות כשמלאי מתחיל להיגמר.',
      aboutOrdersTitle: 'הזמנות לספקים',
      aboutOrdersDesc: 'צור הזמנות ישירות מרשימת המלאי. קבץ מוצרים לפי ספק וייצא להזמנה ב-PDF.',
      aboutBarBookTitle: 'ספר הבר',
      aboutBarBookDesc: 'צ׳קליסטים, משימות יומיות לפי ימי שבוע ומתכונים — הכל במקום אחד.',
      aboutDashboardTitle: 'דשבורד',
      aboutDashboardDesc: 'סקירה כללית של פעילות הבר: מוצרים, הזמנות, הכנסות יומיות ותרשים הזמנות לפי ספק.',
      aboutDescription2: 'מבוסס על React, Node.js ו-MongoDB',
      aboutVersion: 'גרסה 1.0',
    },
  },
  en: {
    translation: {
      home: 'Home',
      products: 'Products',
      profile: 'Profile',
      about: 'About',
      barBook: 'Bar Book',
      orders: 'Orders',
      itemsManagement: 'Items Management',
      cart: 'Cart',
      // Landing page
      landingTagline: 'Smart Bar Management — Inventory, Orders & Bar Book In One Place',
      landingLoginTitle: 'Sign In',
      landingSignupTitle: 'Create Account',
      landingLoginBtn: 'Sign In',
      landingSignupBtn: 'Create Account',
      alreadyMember: 'Already A Member? Sign In',
      newUser: 'New Here? Create An Account',
      fullnamePlaceholder: 'Full Name',
      usernamePlaceholder: 'Username',
      passwordPlaceholder: 'Password',
      welcomeMsg: 'Welcome!',
      loginError: 'Invalid Username Or Password',
      featureInventoryTitle: 'Inventory Management',
      featureInventoryDesc: 'Track Products, Prices And Low-Stock Alerts',
      featureOrdersTitle: 'Supplier Orders',
      featureOrdersDesc: 'Create And Manage Orders Directly From Your Inventory',
      featureBarBookTitle: 'Bar Book',
      featureBarBookDesc: 'Checklists, Daily Tasks And Recipes In One Place',
      featureDashboardTitle: 'Dashboard',
      featureDashboardDesc: 'Real-Time Overview Of Your Bar Activity',
      recipes: 'Recipes',
      dailyTask: 'Daily Task',
      day_0: 'Sunday',
      day_1: 'Monday',
      day_2: 'Tuesday',
      day_3: 'Wednesday',
      day_4: 'Thursday',
      day_5: 'Friday',
      day_6: 'Saturday',
      dayPrefix: '',
      dailyTaskFallback: 'Check Stock And Update The Bar Book',
      supplierOrdersSummaryTitle: 'Orders by Supplier & Product',
      supplierOrdersTotalUnits: 'units total',
      supplierOrdersProduct: 'Product',
      supplierOrdersQty: 'Qty',
      statTotalProducts: 'Total Products',
      statAvailableProducts: 'Available Products',
      statLowStock: 'Low Stock',
      statTotalOrders: 'Total Orders',
      statPendingOrders: 'Pending Orders',
      statTodayRevenue: "Today's Revenue",
      lowStockAlerts: 'Low Stock Alerts',
      stockLabel: 'Stock',
      alertThresholdLabel: 'Alert Min',
      viewAllLowStock: 'View All Products With Low Stock',
      recentOrders: 'Recent Orders',
      viewAll: 'View All',
      orderId: 'Order',
      itemsCount: 'Items',
      status_pending: 'Pending',
      status_completed: 'Completed',
      status_delivered: 'Delivered',
      hello: 'Hello',
      logout: 'Logout',
      switchUser: 'Switch User',
      logoutSuccess: 'See You!',
      loginRequired: 'Please Sign In First',
      toggleLanguage: 'Toggle Language',
      openSidebar: 'Open Menu',
      closeSidebar: 'Close Menu',
      barBookTitle: 'Bar Book',
      tabChecklists: 'Checklists',
      tabPages: 'Stock Pages',
      tabDaily: 'Daily Tasks',
      tabRecipes: 'Recipes',
      editMode: 'Edit',
      exitEditMode: 'Done Editing',
      loadingBarBook: 'Loading Bar Book...',
      errorLoadBarBook: 'Error Loading Bar Book',
      dailyTasksTitle: 'Daily Tasks',
      dailyTasksIntro: 'Daily Tasks Are Performed Every Shift. The Task Is Performed By Day Of The Week.',
      dayColumn: 'Day',
      dailyTaskColumn: 'Daily Task',
      clickToEdit: 'Click To Edit',
      deleteRow: 'Delete Row',
      deleteItem: 'Delete Item',
      deleteDay: 'Delete Day',
      addTask: 'Add Task',
      addDay: 'Add Day',
      clearContent: 'Clear Content',
      addPage: 'Add Page',
      pageTitlePlaceholder: 'Page title...',
      confirmDeletePage: 'Delete this page?',
      typeChecklists: 'Checklists',
      typeChecklist: 'Checklist',
      typeDaily: 'Daily Tasks',
      typeStock: 'Stock Table',
      typeRecipes: 'Recipes',
      addList: 'Add List',
      items: 'items',
      selectChecklistPrompt: 'Select a checklist to view',
      addRow: 'Add Row',
      newColumn: 'New Column',
      rename: 'Rename',
      deleteColumn: 'Delete Column',
      newDay: 'New Day',
      dailyTaskPlaceholder: 'Write All Tasks For This Day Here...',
      emptyCell: '(Empty)',
      emptyClickEdit: '(Empty – Click To Edit)',
      confirmClearBarBook: 'Clear All Bar Book Content? All Content Will Be Deleted.',
      recipesTitle: 'Recipes',
      addRecipe: 'Add Recipe',
      loadingRecipes: 'Loading Recipes...',
      noRecipes: 'No Recipes. Add The First One.',
      selectRecipePrompt: 'Select A Recipe To View',
      editRecipe: 'Edit Recipe',
      deleteRecipe: 'Delete Recipe',
      edit: 'Edit',
      delete: 'Delete',
      ingredients: 'Ingredients',
      instructions: 'Instructions',
      editingRecipe: 'Edit Recipe',
      addingRecipe: 'Add Recipe',
      recipeNameLabel: 'Recipe Name',
      recipeNamePlaceholder: 'e.g. Cinnamon Syrup',
      ingredientsLabel: 'Ingredients (One Per Line)',
      instructionsLabel: 'Instructions (One Step Per Line)',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      recipeTitleRequired: 'Recipe Name Is Required',
      minOneIngredient: 'Enter At Least One Ingredient',
      minOneStep: 'Enter At Least One Step',
      confirmDeleteRecipe: 'Delete Recipe',
      ingredientsPlaceholder: 'Sugar water\nCoriander\nPassion fruit puree',
      instructionsPlaceholder: 'Mix the ingredients.\nStrain and finish.',
      // Orders list
      ordersListTitle: 'Orders List',
      noOrders: 'No Orders',
      dateColumn: 'Date',
      filterByDateRange: 'Filter by date range',
      dateFrom: 'From',
      dateTo: 'To',
      applyDateFilter: 'Show',
      clearDateFilter: 'Clear',
      noOrdersInDateRange: 'No orders in selected date range',
      downloadPdf: 'Download PDF',
      deleteOrder: 'Delete Order',
      itemColumn: 'Item',
      quantityColumn: 'Quantity',
      itemRemoved: 'Removed',
      undo: 'Undo',
      removeItemFromOrder: 'Remove Item From Order',
      noItems: 'No Items',
      confirmDeleteOrder: 'Are You Sure You Want To Delete This Order?',
      orderDeletedSuccess: 'Order Deleted Successfully',
      orderDeleteError: 'Error Deleting Order',
      orderUpdatedSuccess: 'Order Updated Successfully',
      orderUpdateError: 'Error Updating Order',
      pdfError: 'Error Creating File',
      noSupplier: 'No Supplier',
      itemNumber: 'Item {{n}}',
      // Items management
      itemsManagementTitle: 'Items Management',
      noProductsInSystem: 'No Products In The System',
      addFirstProduct: 'Add Your First Product',
      addFirstRecipe: 'Add Your First Recipe',
      barBookEmpty: 'Bar Book Is Empty. Click To Get Started.',
      initBarBook: 'Initialize Bar Book',
      category: 'Category',
      allCategories: 'All Categories',
      enterCategory: 'Enter New Category',
      supplier: 'Supplier',
      allSuppliers: 'All Suppliers',
      stock: 'Stock',
      all: 'All',
      inStock: 'In Stock',
      outOfStock: 'Out Of Stock',
      lowStockFilter: 'Low Stock',
      showingProducts: 'Showing {{count}} Of {{total}} Products',
      clearFilters: 'Clear Filters',
      createOrder: 'Create Order ({{n}})',
      importStockExcel: 'Import Stock From Excel',
      uploadDocument: 'Upload Document',
      addProduct: 'Add Product',
      selectOrdersToCreate: 'Select Which Orders To Create',
      createOrderModalDesc: 'Products To Order Are Grouped By Supplier. Check The Suppliers You Want To Send An Order To.',
      productsCount: '{{n}} Products',
      combinedOrderOption: 'Create Combined Order – Merge All Selected Products Into One Order',
      createSelectedOrders: 'Create Selected Orders',
      importStockTitle: 'Import Stock From Excel',
      fileLabel: 'File',
      loading: 'Loading...',
      totalRows: 'Total Rows',
      matchedRows: 'Matched Rows',
      uniqueItemsToUpdate: 'Unique Items To Update',
      unmatchedRows: 'Unmatched Rows',
      showUnmatched: 'Show Unmatched Rows',
      andMore: '... And {{n}} More',
      applyStockUpdate: 'Apply Stock Update',
      close: 'Close',
      editProduct: 'Edit Product',
      addNewProduct: 'Add New Product',
      nameHe: 'Name (Hebrew)',
      nameEn: 'Name (English)',
      description: 'Description',
      selectCategory: 'Select Category',
      noCategoriesAvailable: 'No Categories Available',
      categoriesFromProducts: 'Found {{n}} Categories From Existing Products',
      noCategoriesInProducts: 'No Categories Found In Existing Products',
      price: 'Price',
      stockQuantity: 'Stock',
      optimalStock: 'Optimal',
      imageUrl: 'Image (URL)',
      availableForOrder: 'Available For Order',
      update: 'Update',
      save: 'Save',
      nameColumn: 'Name',
      orderQuantity: 'Order Qty',
      actions: 'Actions',
      noProductsMatchFilters: 'No Products Match The Selected Filters',
      remove: 'Remove',
      confirmDeleteItem: 'Are You Sure You Want To Delete This Item?',
      itemDeletedSuccess: 'Item Deleted Successfully',
      itemDeleteError: 'Error Deleting Item',
      itemSavedSuccess: 'Item Added Successfully',
      itemUpdatedSuccess: 'Item Updated Successfully',
      itemSaveError: 'Error Saving Item',
      optimalUpdated: 'Optimal Quantity Updated',
      optimalUpdateError: 'Error Updating Optimal Quantity',
      stockUpdated: 'Stock Updated',
      stockUpdateError: 'Error Updating Stock',
      noProductsToOrder: 'No Products To Order',
      selectAtLeastOneSupplier: 'Please Select At Least One Supplier',
      combinedOrderLabel: 'Combined Order',
      orderCreatedProducts: 'Order Created – {{n}} Products',
      ordersCreatedProducts: '{{c}} Orders Created – {{n}} Products',
      createOrdersError: 'Error Creating Orders',
      stockUpdatedSuccess: 'Stock Updated Successfully',
      stockUpdateError: 'Error Updating Stock',
      readFileError: 'Error Reading File',
      noCategory: 'No Category',
      noValidRows: 'No Valid Rows Found. Make Sure There Are Name + Stock (Quantity) Columns.',
      // Order page (cart)
      cartTitle: 'Shopping Cart',
      cartEmpty: 'Cart Is Empty',
      supplierLabel: 'Supplier',
      quantityLabel: 'Quantity',
      totalLabel: 'Total',
      checkoutNow: 'Checkout Now (By Supplier)',
      clearCart: 'Clear Cart',
      // Products / menu page
      cannotLoadProducts: 'Cannot Load Products',
      cannotLoadItemDetails: 'Cannot Load Item Details',
      itemNotFound: 'Item Not Found',
      searchSectionTitle: 'Search',
      categoriesFilterTitle: 'Categories',
      searchProductsPlaceholder: 'Search Products...',
      clearSearch: 'Clear Search',
      addToCart: 'Add To Cart',
      available: 'Available',
      unavailable: 'Unavailable',
      allCategoriesFilter: 'All',
      paginationPrev: 'Previous',
      paginationNext: 'Next',
      noItemsFound: 'No Items Found',
      addToCartButton: 'Add To Cart',
      category_ALCOHOL: 'Alcohol',
      category_WINE: 'Wine',
      chartTitle: 'Items Ordered Per Supplier Per Day',
      chartItemsAxis: 'Item Count',
      chartDateAxis: 'Date',
      chartItemsSuffix: 'Items',
      noOrderDataYet: 'No Order Data To Display Yet.',
      // Profile
      profileTitle: 'Profile',
      profileFullname: 'Full Name',
      profileUsername: 'Username',
      profileRole: 'Role',
      profileMemberSince: 'Member Since',
      role_admin: 'Admin',
      role_manager: 'Shift Manager',
      role_bartender: 'Bartender',
      profileNavLink: 'Profile',
      profileCompany: 'Company',
      profileDatabase: 'Database',
      // Signup — company name
      companyNameLabel: 'Company Name',
      companyNamePlaceholder: 'e.g. Bandit',
      companyNameHelp: 'Sets The Database Name For Your Bar',
      companyNameError: 'Invalid Company Name. Use Letters, Numbers And Spaces Only.',
      // Profile settings
      settingsTitle: 'Settings',
      settingsLanguage: 'Language',
      // About page
      aboutTagline: 'Smart Bar Management',
      aboutSubtitle: 'Inventory, Orders And Bar Book — All In One Place',
      aboutDescription: 'BarOS Is Built For Bar Professionals Who Want To Manage Their Bar In An Organized, Efficient Way. Clean Dark Interface With Full Hebrew And English Support.',
      aboutFeaturesTitle: 'Features',
      aboutInventoryTitle: 'Inventory Management',
      aboutInventoryDesc: 'Track All Products, Prices And Stock Levels In Real Time. Get Alerts When Stock Runs Low.',
      aboutOrdersTitle: 'Supplier Orders',
      aboutOrdersDesc: 'Create Orders Directly From Your Inventory List. Group Items By Supplier And Export To PDF.',
      aboutBarBookTitle: 'Bar Book',
      aboutBarBookDesc: 'Checklists, Daily Tasks By Day Of The Week, And Recipes — All In One Place.',
      aboutDashboardTitle: 'Dashboard',
      aboutDashboardDesc: 'Overview Of Bar Activity: Products, Orders, Daily Revenue And Orders Chart By Supplier.',
      aboutDescription2: 'Built With React, Node.js And MongoDB',
      aboutVersion: 'Version 1.0',
    },
  },
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    supportedLngs: ['he', 'en'],
    lng: 'en',
    debug: false,
    interpolation: {
      escapeValue: false,
    },
  })

function setDocumentLanguage(lng) {
  const lang = lng || i18n.language
  if (document.documentElement) {
    document.documentElement.lang = lang
    document.documentElement.setAttribute('dir', lang === 'he' ? 'rtl' : 'ltr')
  }
}
setDocumentLanguage()
i18n.on('languageChanged', setDocumentLanguage)

export default i18n
